### ISSUE TITLE
Cannot find the list all orders

### ISSUE THREAD

**Issue by caiqueacct** [bennycode/coinbase-pro-node#339]
Hi

How can I get the list of all orders?

I found the getOrder but require an orderId

Thanks

**Comment by bennycode** [comment]
Hi @caiqueacct, according to the Coinbase Pro documentation, you can [list only open orders](https://docs.pro.coinbase.com/#list-orders). This is possible using [getOpenOrders](https://github.com/bennycode/coinbase-pro-node/blob/v2.14.0/src/order/OrderAPI.ts#L145). If you want to list filled orders, then you can use [getFillsByProductId](https://github.com/bennycode/coinbase-pro-node/blob/v2.14.0/src/fill/FillAPI.ts#L60).

Hope this helps!

Best,
Benny
