### ISSUE TITLE
401 request timestamp expired

### ISSUE THREAD

**Issue by alexander-hagen** [bennycode/coinbase-pro-node#354]
I have a function that is called once per minute to refresh account balances:

newbalances=await account._client.rest.account.listAccounts();

This function mostly has no issues, but I get a "request timestamp expired" message after some time. I haven't been able to catch the error and the program thus terminates unexpectedly.

I have noticed that in these cases CB-ACCESS-TIMESTAMP has a value of NaN. I don't know if this is the cause, or  not.

    headers: {
      Accept: 'application/json, text/plain, */*',
      'CB-ACCESS-KEY': '*** VALID KEY ***',
      'CB-ACCESS-PASSPHRASE': '*** VALID PASS *** ',
      'CB-ACCESS-SIGN': '*** VALIG SIGNATURE ***',
      'CB-ACCESS-TIMESTAMP': NaN,
      'User-Agent': 'axios/0.21.0'
    },

and the response is

  response: {
    status: 401,
    statusText: 'Unauthorized',
    ...
    data: { message: 'request timestamp expired' }
  },

How to modify ErrorUtil.js to catch request timestamp expired so that the request is tried. I also have 400 request timeout, which I would also like handle in ErrorUtil.js, and have them retried. 
[401 Unauthorized - Timestamp expired.txt](https://github.com/bennycode/coinbase-pro-node/files/5791507/401.Unauthorized.-.Timestamp.expired.txt)

**Comment by bennycode** [comment]
Hi @alexander-hagen, thank you very much for taking the time to report this problem.

The "coinbase-pro-node" API client has retry conditions on which requests are rescheduled:

https://github.com/bennycode/coinbase-pro-node/blob/452e0d7da7ae4c5ea7b6f8f99dc0505b6baf5b84/src/client/RESTClient.ts#L66-L68

From what you are reporting, it looks like there is an issue with the timestamp calculation because "CB-ACCESS-TIMESTAMP" is `NaN`:

https://github.com/bennycode/coinbase-pro-node/blob/452e0d7da7ae4c5ea7b6f8f99dc0505b6baf5b84/src/client/RESTClient.ts#L95-L101

Here is how the timestamp gets calculated:

https://github.com/bennycode/coinbase-pro-node/blob/452e0d7da7ae4c5ea7b6f8f99dc0505b6baf5b84/src/auth/RequestSigner.ts#L21

The `clockSkew` is returned from a REST endpoint at Coinbase:

https://github.com/bennycode/coinbase-pro-node/blob/452e0d7da7ae4c5ea7b6f8f99dc0505b6baf5b84/src/CoinbasePro.ts#L74

Do you have any chance to log `clockSkew`, so we can check if it always returns a `number`?

**Comment by bennycode** [comment]
The time endpoint for Coinbase Pro is public: https://api.pro.coinbase.com/time

It returns an object in the following format:

```
{
  "epoch": 1610478925.749,
  "iso": "2021-01-12T19:15:25.749Z"
}
```

The "epoch" property is used in the `getClockSkew` calculation:

https://github.com/bennycode/coinbase-pro-node/blob/452e0d7da7ae4c5ea7b6f8f99dc0505b6baf5b84/src/time/TimeAPI.ts#L32-L33

If, for whatever reason, the "epoch" property is `undefined`, then we will have the following scenario:

> undefined - Date.now() / 1000 = NaN

So my best guess is, that Coinbase's time endpoint fails to respond in time and screws up the calculation. It might be that your IP gets rate-limited. How often do you query `listAccounts()`?

**Comment by alexander-hagen** [comment]
Hello Benny.

Here are the requested details. First line has results from the coinbase time API, Date().now, and time.epoch-now, as calculated in getClockSkew(). Second line is the same CLockSkew, but logged from class CoimbasePro.

*** {"iso":"2021-01-12T21:20:23.936Z","epoch":1610486423.936}:1610486423.994:-0.05799984931945801 ***
*** ClockSkew: -0.05799984931945801 ***
*** {"iso":"2021-01-12T21:20:23.977Z","epoch":1610486423.977}:1610486424.08:-0.10299992561340332 ***
*** ClockSkew: -0.10299992561340332 ***
*** "{\"iso\":\"2021-01-12T21:20:24Z\",\"epoch\":1610486424.}":1610486424.105:NaN ***
*** ClockSkew: NaN ***
*** {"iso":"2021-01-12T21:20:23.981Z","epoch":1610486423.981}:1610486424.11:-0.12899994850158691 ***
*** ClockSkew: -0.12899994850158691 ***

The output from the REST API still needs to be unescaped. I noticed that the milliseconds for the epoch in the erroneous line is zero. The epoch has a decimal point, but no digits behind.

**Comment by bennycode** [comment]
Thank you Alexander, this is very valuable logging!

I created a table out of your data:

| TimeSkew | Date().now / 1000 | getClockSkew | ClockSkew |
| --- | --- | --- | --- |
| {"iso":"2021-01-12T21:20:23.936Z","epoch":1610486423.936} | 1610486423.994 | -0.05799984931945801 | -0.05799984931945801 |
| {"iso":"2021-01-12T21:20:23.977Z","epoch":1610486423.977} | 1610486424.08 | -0.10299992561340332 | -0.10299992561340332 |
| {"iso":"2021-01-12T21:20:24Z","epoch":1610486424.} | 1610486424.105 | NaN | NaN |
| {"iso":"2021-01-12T21:20:23.981Z","epoch":1610486423.981} | 1610486424.11 | -0.12899994850158691 | -0.12899994850158691 |

I also made a potential fix, which parses any number (such as the strange `1610486424.`) as floating point numbers:

https://github.com/bennycode/coinbase-pro-node/blob/89e72954f096a6960b9c44bec1afaefa1dbd9186/src/time/TimeAPI.ts#L33

Can you please tryout [**v2.16.1**](https://www.npmjs.com/package/coinbase-pro-node/v/2.16.1) and tell me if it fixes the error?

**Comment by alexander-hagen** [comment]
Hello Benny, This doesn't work yet. Logging says {epoch} is undefined.  Your test case uses the unescaped value, while the value returned by the API is still escaped. When the milliseconds of the epoch are zero, then the API returns an unescaped string, while in all other cases it returns an escaped string.

The formatting got lost when I pasted the data. Here is the string that is returned for a 0 ms epoch:
TimeSkew returned is "{\\"iso\\":\\"2021-01-12T21:20:24Z\\",\\"epoch\\":1610486424.}".

For a non-zero ms, the TimeSkew returned is {"iso":"2021-01-12T21:20:24Z","epoch":1610486424.123}

**Comment by bennycode** [comment]
Ouch. If your observation is true, then this means that Coinbase Pro doesn't always send a response with content-type "application/json; charset=utf-8". 

I am enforcing now requesting JSON payloads:

https://github.com/bennycode/coinbase-pro-node/blob/074606066c4aa4d654ac37fe4ea48186a35cd8aa/src/time/TimeAPI.ts#L23-L28

It's available in **v2.16.2**. Hope this helps!

If there are still problems, then we need to log `typeof` from the return value of `getTime()`. It might be "string".

**Comment by alexander-hagen** [comment]
It still returns an undefined. The issue is that response.data returns an object for non-zero ms for epoch, and returns a string for a zero ms epoch.

**Comment by alexander-hagen** [comment]
I'm testing with this. for getClockShew(). So far this looks to be working, although it probably can be programmed more efficient.
<pre><code>    getClockSkew() {
        return __awaiter(this, void 0, void 0, function* () {
            const time = yield this.getTime();
            const now = Date.now() / 1000;
            if(typeof(time)==="string") { var epoch = parseFloat(time.match(/epoch":(.*)\./i)[1]); console.log("\n\n======\n====== EPOCH: "+epoch+" ======\n======\n\n"); } else { var {epoch}=time };            
            return epoch - now;
        });
    }</code></pre>

**Comment by bennycode** [comment]
Ah, great! I will make another PR later today to integrate it.

Can you test if you can do something like this?

```js
if (typeof time ==="string") {
  time = JSON.parse(time);
  var epoch = time.epoch;
}
```

**Comment by alexander-hagen** [comment]
I tried that yesterday. The JSON.parse gives an error because of the decimal point without any decimal digits following. JSON.parse will only work if the decimal point is removed, or a zero is added after the decimal point. That's how I ended up with the RegEx solution.

**Comment by bennycode** [comment]
Nice! 

If you like, you can also open a PR here and apply your changes to the "main" branch. 

Just edit this file: 
- https://github.com/bennycode/coinbase-pro-node/blob/main/src/time/TimeAPI.ts

**Comment by alexander-hagen** [comment]
The PR complained about time.match being invalid. I'm more into NodeJs than typescript. It works in TimeAPI.js. Not sure how to out this in TimeAPI.ts

**Comment by bennycode** [comment]
I checked your PR and made the necessary changes. Please tryout coinbase-pro-node@2.16.3. 

And thanks for being patient with me!

**Comment by alexander-hagen** [comment]
Thanks. I'm happy we managed to fix it.
