### ISSUE TITLE
feat: useSandbox optional

### ISSUE THREAD

**Issue by alexander-hagen** [bennycode/coinbase-pro-node#365]
In 2.15.0 and earlier, the useSandbox parameter was optional in <pre><code>this._client=new CoinbasePro({ apiKey: account.apikey, apiSecret: account.secret, passphrase: account.passphrase})</code></pre>

From 2.16.0 the useSandbox parameter is mandatory <pre><code>this._client=new CoinbasePro({ apiKey: account.apikey, apiSecret: account.secret, passphrase: account.passphrase, useSandbox: false })</code></pre>

Can we make useSandbox optional again and have it default to false?

**Comment by bennycode** [comment]
Hey Alexander, my intention with making the sandbox flag required is to make people read the readme. 😁 I also want that users really make sure they want to use the production environment of Coinbase Pro. This should prevent users from headlessly running trades in production / real-life.
