### ISSUE TITLE
listAccounts() returns getTime(), sometimes

### ISSUE THREAD

**Issue by alexander-hagen** [bennycode/coinbase-pro-node#368]
Usually, listAccounts() works fine and returns the balances of the requested account.

<pre><code>
newbalances=await account._client.rest.account.listAccounts();
if(newbalances.length===undefined) { console.log("Newbalances:"+JSON.stringify(newbalances)); };
</code></pre>

Sometimes it returns getTime(). <code>Newbalances:{"iso":"2021-01-15T09:22:55.205Z","epoch":1610702575.205}</code>

**Comment by alexander-hagen** [comment]
Troubleshooting so far shows that this occurs at times when rate limiting is active.

**Comment by bennycode** [comment]
Hi @alexander-hagen, I guess that there is a call to `getTime()` every time you make a call to `listAccounts()`, am I right with that? If yes, then we can maybe cache the result of `getTime()` and only do it whenever this time skew gets outdated. This could save a lot of requests to Coinbase Pro.

**Comment by alexander-hagen** [comment]
For every REST call, there also is a request to GET /time. I was thinking to get rid of skew altogether as CoinbasePro permits requests with up to 30 seconds time discrepancy. Alternatively, periodically updating is perhaps a better alternative.

**Comment by bennycode** [comment]
Let's do the caching approach: We fetch the skew once and when Coinbase Pro reports that the time is out of sync, we will update it.

**Comment by alexander-hagen** [comment]
I now also have a case where it happens while there no rate limiting. It still may be related to the GET /time though. I will do some tests without the GET /time and let you know

**Comment by bennycode** [comment]
Hi @alexander-hagen, I built [caching for the time skew](https://github.com/bennycode/coinbase-pro-node/pull/373/files). Can you please try [coinbase-pro-node@2.16.4](https://www.npmjs.com/package/coinbase-pro-node/v/2.16.4)?

**Comment by alexander-hagen** [comment]
OK, let me have a try. I have been running with local time only for the past past week and didn't have any the issue since then:

<pre><code>    getTime() {
        return __awaiter(this, void 0, void 0, function* () {
          const now=new Date();
          const epoch=now / 1000;
          const iso=now.toISOString();
          const data={"iso": now,"epoch": epoch};
          return data;
        });
    }</code></pre>

**Comment by alexander-hagen** [comment]
Looks good. Great job!
