### ISSUE TITLE
Return value must be between brackets

### ISSUE THREAD

**Issue by alexander-hagen** [bennycode/coinbase-pro-node#388]
When returning a structure in a function in NodeJS, the returnvalue must be between brackets. Otherwise it returns {}.  There are 7 files with 10 occurences where this should be fixed.

I tried to create a pull request, but it removed the brackets, or assigning the structure to a variable first

**Comment by bennycode** [comment]
Hi @alexander-hagen, I am using the library on a daily basis and I don't think that there is something wrong with the return values. Assigning a return value to a constant first, doesn't change the behavior.

**Comment by alexander-hagen** [comment]
@bennycode When I use <pre><code>
const maxlimit=100;
var newtrades=await market._client.rest.product.getTrades(market._product_id, { limit: maxlimit });
console.log(JSON.stringify(newtrades));</code></pre>
I get <code>{}</code> when the return value is  not between brackets. I get the correct data structure when it is between brackets. My NodeJS version is 15.5.0. Any ideas?
