### ISSUE TITLE
No valid WebSocket class provided

### ISSUE THREAD

**Issue by caiqueacct** [bennycode/coinbase-pro-node#395]
Hi

I'm trying to use coinbase-pro-node in a Vue app but I'm receiving the following error when trying to use the websocketclient

Error: No valid WebSocket class provided
    _connect reconnecting-websocket-mjs.js:506
    ReconnectingWebSocket reconnecting-websocket-mjs.js:203
    connect WebSocketClient.js:159
    _callee$ VCoinbaseSocket.vue:49
    Babel 10
    VueJS 4
    click vuetify.js:2564
    VueJS 33
VCoinbaseSocket.vue:51

Any ideas?

Thanks

**Comment by bennycode** [comment]
The "coinbase-pro-node" library was developed to run in a Node.js environment. However, it is possible to use the package in a browser environment (where Vue.js frontend apps are running) but you have to be aware of some consequences:

- REST calls are likely to be blocked by the browser's CORS policy, so you have to start your browser with [disabled web security](https://stackoverflow.com/questions/3102819/disable-same-origin-policy-in-chrome) or use a proxy (i.e. [webpack's dev server proxy](https://webpack.js.org/configuration/dev-server/#devserverproxy)) to communicate with Coinbase Pro's backend.
- WebSocket connections are established using the ["ws" package](https://github.com/websockets/ws) (Node.js), but the browser comes with a [native WebSocket](https://developer.mozilla.org/en-US/docs/Web/API/WebSocket) implementation, so the constructor passed to `ReconnectingWebSocket` must be changed ([Example](https://github.com/pladaria/reconnecting-websocket/tree/v4.4.0#sample-with-custom-options)).

Are you just having problems with establishing a WebSocket connection or do REST calls also fail for you?

**Comment by caiqueacct** [comment]
On node everything working fine. The problem is just with WebSocket on the browser. 

I tried to use ws = new WebSocket('coinbase') but it didn't work.

I'll try the example using ReconnectionWebSocket.

Thanks
