### ISSUE TITLE
listProfiles is missing support for active parameter

### ISSUE THREAD

**Issue by alexander-hagen** [bennycode/coinbase-pro-node#397]
The listProfiles API supports an active parameter. See [here](https://docs.pro.coinbase.com/#list-profiles)

This parameter is missing. See [here](https://github.com/bennycode/coinbase-pro-node/blob/dda465ded30844abab220ce3532b7cac67cc1f17/src/profile/ProfileAPI.ts#L35)

**Comment by bennycode** [comment]
Thanks for the hint! I added the `active` parameter to v2.17.2. 😊
