### ISSUE TITLE
API not being called within express router

### ISSUE THREAD

**Issue by ryanbrwr** [bennycode/coinbase-pro-node#404]
Not sure if this is the right place to get help with this, but figured I'd give it a shot. Trying to make a call to this library on an api request from express, but the client never seems to actually do the request, just kinda hangs. 

```
var express = require("express");
var router = express.Router();
var { CoinbasePro } = require('coinbase-pro-node');

router.get("/", function (req, res, next) {
    let query = req.query

    var auth = {
        apiKey: query.api_key,
        apiSecret: query.secret_key,
        passphrase: query.passphrase,
    };
    
    var client = new CoinbasePro(auth);

    client.rest.account.listAccounts().then(accounts => {
        const message = `You can trade "${accounts.length}" different pairs.`;
        res.send(message)

    }).catch((error) => {
        res.send(error)
    })
});

module.exports = router;
```
any explanation why anything else works in this route except this library would be appreciated

**Comment by ryanbrwr** [comment]
I see the section about setting up a proxy, but I want to do all of the functions with Coinbase inside of the backend, how can I get this to work?

**Comment by bennycode** [comment]
Hi @ryanbrwr, you need to set a `useSandbox` property to `auth`. Set it to `false`, if you want to use the Coinbase Pro production environment.

**Comment by ryanbrwr** [comment]
Great I'll try this out! Appreciate the help with this simple question lol

**Comment by bennycode** [comment]
@ryanbrwr, have you been successful with it?

**Comment by ryanbrwr** [comment]
yes I was successful, thank you!
