### ISSUE TITLE
Are websocket L2 events supported?

### ISSUE THREAD

**Issue by justinsoliz** [bennycode/coinbase-pro-node#405]
I was reviewing the websocket client code and didnt see where L2 updates were being returned and just wanted to double check if they are in fact supported?

https://github.com/bennycode/coinbase-pro-node/blob/e6787a819d21890be400f2682825b2edbed60933/src/client/WebSocketClient.ts#L126-L184

**Comment by bennycode** [comment]
Hi @justinsoliz, it's supported by the library to subscribe to L2 updates. There is also a type for these events:

https://github.com/bennycode/coinbase-pro-node/blob/c4d6ec6218b336d5dd071dcb13e96d152fcfe03c/src/client/WebSocketClient.ts#L113-L114

Are you missing anything in particular?

Best,
Benny

**Comment by justinsoliz** [comment]
Thanks for the follow up here. It was confusion on my end but I'm now able to receive the expected updates.
