### ISSUE TITLE
Is there any support for withdrawal to coinbase account?

### ISSUE THREAD

**Issue by ryanbrwr** [bennycode/coinbase-pro-node#406]
Just wondering if there was / will be withdrawal to coinbase account possible with this library

**Comment by bennycode** [comment]
Yes, it's available: https://bennycode.com/coinbase-pro-node/#/classes/_withdraw_withdrawapi_.withdrawapi

**Comment by ryanbrwr** [comment]
That seems to only be crypto withdrawal to another wallet. I'm talking about /withdrawals/coinbase-account, and not crypto withdrawal
