### ISSUE TITLE
Getting internal server error on crypto transfer

### ISSUE THREAD

**Issue by ryanbrwr** [bennycode/coinbase-pro-node#407]
I've been getting an internal server error for a couple of hours on a crypto transfer. 

```
client.rest.withdraw.postCryptoWithdrawal(0.0000001, 'BTC', '339FL7Xoh3WmrcJmo6ejeLfBVZgus2fTdx', true).then((data) => {
    console.log('===============')
    console.log('Transfering DATA')
    console.log(data)
}).catch((error) => {
    console.log('===============')
    console.log('Transfering DATA')
    console.log(error)
})
```

Do we have support for /withdraw/coinbase-account? That would be much easier, and have no fees. Thanks again!

**Comment by ryanbrwr** [comment]
I dont think I was fully understood when I asked if there was support for coinbase account transfer. There is an endpoint for it and it's different than postCryptoWithdraw.

**Comment by bennycode** [comment]
Hi @ryanbrwr, I am happy that you bring this up. 

The endpoints `/withdrawals/coinbase-account` & `/withdrawals/payment-method` have been missing. Those endpoints will get added with this PR: https://github.com/bennycode/coinbase-pro-node/pull/408

You will be able to access the different endpoints with the next release by using:

- `client.rest.withdraw.withdrawToCoinbaseAccount`
- `client.rest.withdraw.withdrawToCryptoAddress`
- `client.rest.withdraw.withdrawToPaymentMethod`

There will be also:

- `client.rest.withdraw.getPaymentMethods`

Thank you for your report!

**Comment by ryanbrwr** [comment]
Awesome thank you! Do you have any possibility why the code above returned an internal server error though?

**Comment by bennycode** [comment]
From what I can see in your report, you have set the `destinationTag` (fourth parameter) to `true`. That's wrong. It must be a `string`.

**Comment by ryanbrwr** [comment]
ah I was trying to set the addFeeToTransaction parameter, what should I do for the destinationTag in this case??

**Comment by bennycode** [comment]
Just keep it blank / set it to `undefined`.

**Comment by bennycode** [comment]
You can use v2.18.0 now. With this version, `client.rest.withdraw.postCryptoWithdrawal` changes to `client.rest.withdraw.withdrawToCryptoAddress` and you have to pass in the amount as a `string` (not `number` anymore).
