### ISSUE TITLE
Querying ALL Orders

### ISSUE THREAD

**Issue by jonathansampson** [bennycode/coinbase-pro-node#431]
An opportunity to improve documentation:

Related to #339, I was curious how to query for _all orders_ (rather than for _open_ orders alone). It seemed like the only parameters we could pass with the request were _pagination_ values. After a quick scan of the source I realized a general query-string is created from whatever object is passed as the _pagination_ object (thanks to loose restrictions on the interface). As such, `getOpenOrders({ status: 'all' })` would suffice to retrieve all orders.

https://github.com/bennycode/coinbase-pro-node/blob/a3ed45ba7683a717c8d295f0baf9247dbef69376/src/order/OrderAPI.ts#L145-L155

**Comment by bennycode** [comment]
Hi @jonathansampson, can you point me to Coinbase's documentation for `{ status: 'all' }`? If it is a valid query string, then I will add it to the list of accepted params for `getOpenOrders`.

**Comment by jonathansampson** [comment]
@bennycode Certainly, see https://docs.pro.coinbase.com/#list-orders.

![image](https://user-images.githubusercontent.com/815158/111039264-b5c76500-83f2-11eb-89d8-7ec3ef109612.png)

**Comment by bennycode** [comment]
I think extending the existing parameter is a good idea. What's your take on that? https://github.com/bennycode/coinbase-pro-node/pull/432/files

**Comment by jonathansampson** [comment]
@bennycode Thanks! I added a single comment for your consideration.

**Comment by bennycode** [comment]
Thank you! 🤝 Fixed with https://github.com/bennycode/coinbase-pro-node/pull/432
