### ISSUE TITLE
Angular app throws problem because of Crypto dependency

### ISSUE THREAD

**Issue by ErraticFox** [bennycode/coinbase-pro-node#440]
Hello, I was really looking forward to using this in my Angular project as it has TypeScript support and that's a huge plus for me, but when using it in something browser based, it doesn't work because of the Crypto dependency from what I gathered. Do you have any solution to this?

**Comment by bennycode** [comment]
Hi @ErraticFox, with "webpack" you can make use of "coinbase-pro-node" in your frontend application. But be aware of CORS limitations! I wrote intructions about it here: https://github.com/bennycode/coinbase-pro-node#web-frontend-applications
