### ISSUE TITLE
OrderStatus.DONE should be a valid OrderStatus for listing orders

### ISSUE THREAD

**Issue by XaeroDegreaz** [bennycode/coinbase-pro-node#441]
Docs: https://docs.pro.coinbase.com/#list-orders

Your API is called `getOpenOrders`, and I suppose it makes sense to have only open statuses available, but it seems that you may be missing a simple `getOrders` method that will accept any `OrderStatus`.

It would be nice to be able to use `OrderStatus.DONE` without having to use `@ts-ignore`. I could just use `all` for my purposes, but I feel like that could cause problems without extra filtering at some point.

**Comment by bennycode** [comment]
Hey @XaeroDegreaz, I renamed `getOpenOrders` to `getOrders` in v2.20.0 and enabled using `OrderStatus.DONE` in the `query.status` parameter. Please give it a try! 🍾

**Comment by XaeroDegreaz** [comment]
Thanks for the response. Isn't this a breaking change, though? Perhaps for backwards compatibility for everyone else, you could just make a separate `getOrders` method in addition to the `getOpenOrders` one. `getOpenOrders` could just be a convenience method that calls `getOrders` with whatever `OrderStatus`' are passed to it, or the defaults it already provides.

Either that or maybe update the version to `3.0.0` o_O?

Some helpful semantic versioning resources:
https://semver.org/
https://docs.npmjs.com/about-semantic-versioning

**Comment by bennycode** [comment]
Hi @XaeroDegreaz, I don't see much value in having a "convenience" method as it will just cost extra maintenance for no extra functionality. I also don't want to have deprecated functions inside of the code base. Deprecated functions are nothing but dust and I like to cleanup dust. Thanks to TypeScript, everyone using this library with TypeScript will be informed that the `getOpenOrders` is no more and then you can see from the [CHANGELOG](https://github.com/bennycode/coinbase-pro-node/blob/main/CHANGELOG.md) what has been changed.

**Comment by bennycode** [comment]
To support JavaScript developers, using "coinbase-pro-node", I have just deprecated v2.20.0 with a notice to use v3:

> npm deprecate coinbase-pro-node@2.20.0

Starting from v3, this package follows [Semantic Versioning](https://semver.org/) to fit well into npm's ecosystem. Thanks for proving your take on this, @XaeroDegreaz.

You can find the latest version here:

- https://www.npmjs.com/package/coinbase-pro-node/v/3.0.0

**Comment by XaeroDegreaz** [comment]
Thanks for the work, great library! I think this is safe to close now
