### ISSUE TITLE
getOrders() returns 401

### ISSUE THREAD

**Issue by Rossez** [bennycode/coinbase-pro-node#450]
I was using getOpenOrders() without problems. After change to getOrders() I get 401 error. No other change made. I don't pass any params to getOrders().

Side question: when the autogenerated API reference is updated? It still references getOpenOrders(). Thank you.

**Comment by bennycode** [comment]
@Rossez, thank you for your report! It also looks like the docs are not published correctly since the latest update of "docsify". They are showing [getOpenOrders](https://bennycode.com/coinbase-pro-node/#/classes/_order_orderapi_.orderapi?id=getopenorders) but should show `getOrders()`. I will debug this.

**Comment by Rossez** [comment]
Hi @bennycode, getOrders() with no params now works ok (I will check passing some params as well). API docs seems ok, however there is an issue with the link to a page with OrderListQueryParam interface. It gives 404 error.

**Comment by bennycode** [comment]
Happy to hear that `getOrders()` works now!

Regarding the API pages: You have very sharp eyes. I just fixed the incorrect links by using relative paths. The interface definition can now be viewed here: https://bennycode.com/coinbase-pro-node/#/interfaces/orderlistqueryparam

Thanks again for bringing up these issues to me. I hope you will find "coinbase-pro-node" useful. If you are happy with it, please give it a star: https://github.com/bennycode/coinbase-pro-node/stargazers

Wishing you much success with Bitcoin & Co.!
