### ISSUE TITLE
Better error surfacing

### ISSUE THREAD

**Issue by jdgriffith** [bennycode/coinbase-pro-node#476]
I'm getting a 400 error message when using your library but nothing very specific beyond that. Is there way to surface the errors a little better on the `rest` calls?

Thanks!

**Comment by bennycode** [comment]
Errors are thrown as instances of `AxiosError` which have all information that is available. Can you post the code that you have been trying?

**Comment by jdgriffith** [comment]
Oh good to know! I I saw in your code after some digging that the error was being returned. I merely need to operate/log the `error.request` and `error.response` (or something more granular such as `error.response.data`). Thanks again!

Btw Is there a function to get a list of closed orders with your API client?

**Comment by bennycode** [comment]
Happy that you found what you were looking for.

For the orders: You can checkout the `ProductAPI`. It provides a function called `getProductOrderBook`, which will return you all orders from the exchange. If you just want to get your own closed orders, you can call:

```ts
const orders = await client.rest.order.getOrders({
  status: ["done"]
});
```

**Comment by jdgriffith** [comment]
Thanks for the guidance!
