### ISSUE TITLE
price property does not exist on place order response.

### ISSUE THREAD

**Issue by javonclarke** [bennycode/coinbase-pro-node#503]
node_version: 14
typescript_version: 4.2.4
coinbase_pro_node_version: 3.0.4

I'm currently placing a new order like this:

```javascript
const orderResponse = await client.rest.order.placeOrder({...});
```
orderResponse : 
```javascript
{
  id: '8f3214cf-0db3-4c25-81b5-f7a05f863104',
  product_id: 'BTC-USD',
  side: 'buy',
  stp: 'dc',
  funds: '199.00497512',
  specified_funds: '200',
  type: 'market',
  post_only: false,
  created_at: '2021-05-25T01:44:22.982286Z',
  fill_fees: '0',
  filled_size: '0',
  executed_value: '0',
  status: 'pending',
  settled: false
}
```

Based on the Coinbase docs and the type definitions in the library, there should be a `price` property on the results, but there isn't one.

**Comment by bennycode** [comment]
Hi @javonclarke, you have place a "market" order. Can you check if you get a price property returned when placing a "limit" order?

**Comment by javonclarke** [comment]
You're right, the price isn't returned on the market order.
