### ISSUE TITLE
Module uses a vulnerable version of ws

### ISSUE THREAD

**Issue by abir-taheer** [bennycode/coinbase-pro-node#518]
Running an npm audit on the latest version (`3.0.4`) results in the following message:
```
# npm audit report

ws  5.0.0 - 6.2.1 || 7.0.0 - 7.4.5
Severity: moderate
Regular Expression Denial of Service - https://npmjs.com/advisories/1748
fix available via `npm audit fix --force`
Will install coinbase-pro-node@0.2.0, which is a breaking change
node_modules/ws
  coinbase-pro-node  >=0.3.0
  Depends on vulnerable versions of ws
  node_modules/coinbase-pro-node

2 moderate severity vulnerabilities
```

Asking npm to forcefully fix the vulnerability causes it to downgrade the package to version `0.2.0` which obviously isn't ideal.

This was on Windows running Node version `16.3.0` and npm version `7.16.0`

**Comment by abir-taheer** [comment]
The version of ws used in the project is `7.4.5` and upgrading to the latest version `7.4.6` resolves the issue

**Comment by abir-taheer** [comment]
Tried to resolve this on my own and realized the repo was already up to date. I think the version on https://www.npmjs.com/package/coinbase-pro-node is not up to date

**Comment by bennycode** [comment]
Hi @abir-taheer and thanks for making me aware of this issue. I published a new version with updated dependencies. Please test with coinbase-pro-node v3.0.5. Best, Benny

**Comment by abir-taheer** [comment]
Yep, can confirm that the issue is resolved

**Comment by bennycode** [comment]
Great! Please give this project a star if it helps you with your use case: https://github.com/bennycode/coinbase-pro-node/stargazers
