### ISSUE TITLE
Support Github Action to publish a Deno-compatible version at https://deno.land/x

### ISSUE THREAD

**Issue by hjoelr** [bennycode/coinbase-pro-node#626]
@bennycode I was wondering if you'd considering setting up CI/CD like Github Actions to publish a Deno-compatible version of this package on https://deno.land/x? I've been starting to experiment with Deno and would like to try this module on my project. I ran across a project at https://github.com/garronej/denoify that is supposed to automatically create a version of the module that Deno could use. They have instructions on how to set up a Github Action to automatically run Denoify. In the meantime, I'm going to try running Denoify of the module locally to get it working on Deno.

**Comment by hjoelr** [comment]
Okay, this isn't as simple as I was expecting since it appears that all the dependencies would need to be "denoified" as well. I'll close for now and maybe revisit once I get a better handle of the scope of this.

**Comment by bennycode** [comment]
Hi @hjoelr, I would like to provide this library for more ecosystems. Please let me know when you find a way how to make this easily happen. :)
