### ISSUE TITLE
Thanks!

### ISSUE THREAD

**Issue by rkingon** [bennycode/coinbase-pro-node#647]
Just dropping by to say thanks! You saved me hours of integration.

Where is your "Buy a coffee" button??

**Comment by bennycode** [comment]
Hey @rkingon and thank you for your comment. This means very much to me and is the "biggest coffee" that you can get me. It also takes me hours to find a solution to a certain problem and I see it this way: When I spent 10 hours, then the cost of integration is 10 hours but if I can share my solution and a second person profits from it, then the cost of the integration is just 5 hours. So if we all work together, it will get easier for everyone. 😊

If you like, you can follow my YouTube channel to learn more about TypeScript: https://www.youtube.com/typescripttv

Are there any topics that you would like to know more about? I am currently in the process of recording new tutorials. 🎬

**Comment by rkingon** [comment]
Thanks Benny!

I have subscribed to your YouTube, looking forward to checking out some of your content! 

One question I have for you, is would you be interested in any paid/sponsored exchange libraries (such as this coinbase / your binance)? I have built a bot that does a really decent job algo trading and we may want to scale it out to multiple exchanges.

Unclear which exchange we go to from here and when, but figured I would ask :)

Also, super appreciate your trading-signals library.

**Comment by bennycode** [comment]
Hey @rkingon, I am happy to see you in the subscribers list of [TypeScript TV](https://www.youtube.com/typescripttv). It motivates me to publish new content!

I don't have the capacity to built more exchange libraries as I am also developing a trading bot with friends. We are very far in the process and I can tell you that the next logical step would be to add an exchange for the "real" stock market (to trade TSLA, AAPL & others). [Interactive Brokers](https://www.interactivebrokers.com/) is a good fit for that and there is a TypeScript API already on GitHub: https://github.com/stoqey/ib

Wishing you lots of success! 🤖

**Comment by rkingon** [comment]
Funny you say that, cause we were actually in the stock market first and doing well, so expanded to Crypto (cause why not?!). 

We are using [Alpaca](https://alpaca.markets/) right now and had plans on moving to [TradeStation](https://www.tradestation.com/) since they support options.

I'll check out Interactive Brokers, thank you for the recommendation!
