### ISSUE TITLE
Coinbase Pro doesn't exist (tutorial)

### ISSUE THREAD

**Issue by aPinix** [bennycode/coinbase-pro-node#949]
In your `.env.defaults` you have:

```bash
# Your production API key from: https://pro.coinbase.com/profile/api
COINBASE_PRO_API_KEY=""
COINBASE_PRO_API_SECRET=""
COINBASE_PRO_PASSPHRASE=""
```

The [Coinbase Pro link](https://pro.coinbase.com/profile/api) doesn't exist anymore.

I believe **COINBASE_PRO_PASSPHRASE** is also not provided by the **API**.

**Comment by kachurovskiy** [comment]
Yeah, the code in this repo looks good and seems to be pointing to the right URLs but it's confusing that nowhere does it mention Advanced Trade API and instead talks about Pro and passphrase. Coincidentally it doesn't work for me for Advanced Trade except for the WS public data - does it work for you?

**Comment by bennycode** [comment]
There is a discussion here: https://github.com/bennycode/coinbase-pro-node/discussions/783

Unfortunately, Coinbase discontinued the Pro API ([see here](https://www.investopedia.com/what-happened-to-coinbase-pro-7104696)) which is why I will also discontinue this library.
